//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StickMan.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public int PostId { get; set; }
        public int Type { get; set; }
        public string Message { get; set; }
        public string Title { get; set; }
        public bool ReadStatus { get; set; }
        public bool DeleteStatus { get; set; }
        public System.DateTime NotifacationTime { get; set; }
        public int SenderId { get; set; }
        public int RecieverId { get; set; }
    }
}
