//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StickMan.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostUser
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int PostId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public bool IsReply { get; set; }
    
        public virtual StickMan_Users StickMan_Users { get; set; }
        public virtual StickMan_Users_Cast_AudioData_UploadInformation StickMan_Users_Cast_AudioData_UploadInformation { get; set; }
    }
}
