//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StickMan.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StickMan_UsersFriendList
    {
        public int UserID { get; set; }
        public int FriendID { get; set; }
        public int Id { get; set; }
    }
}
